### ISSUE TITLE
ArcadeProvider会解析出LevelIndex为10的成绩

### ISSUE THREAD

**Issue by CCzer** [TrueRou/maimai.py#2]
level_index = LevelIndex(score["level"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 714, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1137, in __new__
    raise ve_exc
ValueError: 10 is not a valid LevelIndex

怀疑是某些宴谱的levelindex的问题？

**Comment by TrueRou** [comment]
已修复，并且修复了其他有关宴谱的潜在问题： d773d6914ec44432c5d3f2e8eeb3e464f1959630
已发布v.0.4.0，更新至v.0.4.0以上即可修复该问题： 7bca81c2479e873858ac7542d55a0ff65790265a
